# Generated by Django 6.0.3 on 2026-03-12 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.DateTimeField()),
                ('reminder_type', models.CharField(choices=[('SUNSCREEN', 'Sunscreen'), ('CLOTHING', 'Clothing'), ('SHADE', 'Shade'), ('GENERAL', 'General')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkinCancerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('age_group', models.CharField(max_length=50)),
                ('incidence_rate', models.FloatField()),
                ('mortality_rate', models.FloatField()),
                ('source', models.CharField(max_length=255)),
                ('skin_tone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.skintone')),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'age_group'], name='core_skinca_year_a03ddb_idx')],
            },
        ),
    ]
