# Generated by Django 6.0.3 on 2026-03-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reminder_skincancerstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerYearlyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('cancer_type', models.CharField(max_length=200)),
                ('cases', models.IntegerField()),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('year', 'region', 'cancer_type')},
            },
        ),
    ]
